# Generated by Django 4.0.4 on 2022-05-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(upload_to='C:\\Users\\Noah Greer\\Desktop\\PycharmProjects\\djangotutorial\\portfolio/media/images'),
        ),
    ]
