# Generated by Django 4.0.4 on 2022-05-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0002_delete_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='C:\\Users\\Noah Greer\\Desktop\\PycharmProjects\\djangotutorial\\portfolio/media/images')),
                ('summary', models.CharField(max_length=200)),
            ],
        ),
    ]
